"""初始化AI英语教学系统数据库

Revision ID: f0c40f107c40
Revises: 
Create Date: 2026-02-02 11:07:53.001297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0c40f107c40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_admin_user_id'), 'organizations', ['admin_user_id'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vocabularies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('part_of_speech', sa.JSON(), nullable=True),
    sa.Column('definitions', sa.JSON(), nullable=True),
    sa.Column('english_definition', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('etymology', sa.String(length=255), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('frequency_level', sa.Integer(), nullable=True),
    sa.Column('related_words', sa.JSON(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('antonyms', sa.JSON(), nullable=True),
    sa.Column('collocations', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabularies_id'), 'vocabularies', ['id'], unique=False)
    op.create_index(op.f('ix_vocabularies_word'), 'vocabularies', ['word'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('knowledge_points', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('favorite_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_contents_difficulty_level'), 'contents', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_contents_exam_type'), 'contents', ['exam_type'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_is_featured'), 'contents', ['is_featured'], unique=False)
    op.create_index(op.f('ix_contents_is_published'), 'contents', ['is_published'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_topic'), 'contents', ['topic'], unique=False)
    op.create_index(op.f('ix_contents_vector_id'), 'contents', ['vector_id'], unique=True)
    op.create_table('lesson_plan_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('template_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plan_templates_id'), 'lesson_plan_templates', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_templates_is_active'), 'lesson_plan_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_lesson_plan_templates_level'), 'lesson_plan_templates', ['level'], unique=False)
    op.create_table('lesson_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('target_exam', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grammar_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leveled_materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ppt_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_notes', sa.Text(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_id'), 'lesson_plans', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_level'), 'lesson_plans', ['level'], unique=False)
    op.create_index(op.f('ix_lesson_plans_status'), 'lesson_plans', ['status'], unique=False)
    op.create_index(op.f('ix_lesson_plans_teacher_id'), 'lesson_plans', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_topic'), 'lesson_plans', ['topic'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_no', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('parent_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('target_exam', sa.String(length=100), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('study_goal', sa.Text(), nullable=True),
    sa.Column('current_cefr_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_no'), 'students', ['student_no'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('qualification', sa.JSON(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('content_vocabulary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('context_position', sa.JSON(), nullable=True),
    sa.Column('is_key_vocabulary', sa.Boolean(), nullable=False),
    sa.Column('is_exam_point', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_vocabulary_content_id'), 'content_vocabulary', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_vocabulary_vocabulary_id'), 'content_vocabulary', ['vocabulary_id'], unique=False)
    op.create_table('knowledge_graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cefr_level', sa.String(length=10), nullable=True),
    sa.Column('exam_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ai_analysis_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_graphs_id'), 'knowledge_graphs', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_graphs_student_id'), 'knowledge_graphs', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_graphs_student_id'), table_name='knowledge_graphs')
    op.drop_index(op.f('ix_knowledge_graphs_id'), table_name='knowledge_graphs')
    op.drop_table('knowledge_graphs')
    op.drop_index(op.f('ix_content_vocabulary_vocabulary_id'), table_name='content_vocabulary')
    op.drop_index(op.f('ix_content_vocabulary_content_id'), table_name='content_vocabulary')
    op.drop_table('content_vocabulary')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_no'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_lesson_plans_topic'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_teacher_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_status'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_level'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    op.drop_index(op.f('ix_lesson_plan_templates_level'), table_name='lesson_plan_templates')
    op.drop_index(op.f('ix_lesson_plan_templates_is_active'), table_name='lesson_plan_templates')
    op.drop_index(op.f('ix_lesson_plan_templates_id'), table_name='lesson_plan_templates')
    op.drop_table('lesson_plan_templates')
    op.drop_index(op.f('ix_contents_vector_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_topic'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_published'), table_name='contents')
    op.drop_index(op.f('ix_contents_is_featured'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_exam_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_difficulty_level'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_vocabularies_word'), table_name='vocabularies')
    op.drop_index(op.f('ix_vocabularies_id'), table_name='vocabularies')
    op.drop_table('vocabularies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_admin_user_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
