"""Add Conversation model

Revision ID: 9a6282cdb4bd
Revises: f0c40f107c40
Create Date: 2026-02-02 12:58:44.145721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6282cdb4bd'
down_revision: Union[str, None] = 'f0c40f107c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.Enum('DAILY_GREETING', 'ORDERING_FOOD', 'ASKING_DIRECTIONS', 'JOB_INTERVIEW', 'SHOPPING', 'MAKING_APPOINTMENTS', 'TRAVEL_PLANNING', 'EMERGENCY_SITUATIONS', name='conversationscenario'), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='conversationstatus'), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_student_id'), 'conversations', ['student_id'], unique=False)
    op.drop_column('content_vocabulary', 'version')
    op.drop_index(op.f('ix_contents_created_by'), table_name='contents')
    op.drop_index(op.f('ix_contents_vector_id'), table_name='contents')
    op.create_index(op.f('ix_contents_vector_id'), 'contents', ['vector_id'], unique=True)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.drop_column('contents', 'version')
    op.drop_index(op.f('ix_knowledge_graphs_student_id'), table_name='knowledge_graphs')
    op.create_index(op.f('ix_knowledge_graphs_student_id'), 'knowledge_graphs', ['student_id'], unique=True)
    op.drop_column('knowledge_graphs', 'version')
    op.drop_column('lesson_plan_templates', 'version')
    op.drop_column('lesson_plans', 'version')
    op.create_index(op.f('ix_organizations_admin_user_id'), 'organizations', ['admin_user_id'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.drop_column('organizations', 'version')
    op.drop_index(op.f('ix_students_student_no'), table_name='students')
    op.create_index(op.f('ix_students_student_no'), 'students', ['student_no'], unique=True)
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.drop_column('students', 'version')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.drop_column('teachers', 'version')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'version')
    op.drop_column('vocabularies', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('teachers', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    op.add_column('students', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    op.drop_index(op.f('ix_students_student_no'), table_name='students')
    op.create_index(op.f('ix_students_student_no'), 'students', ['student_no'], unique=False)
    op.add_column('organizations', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_admin_user_id'), table_name='organizations')
    op.add_column('lesson_plans', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('lesson_plan_templates', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('knowledge_graphs', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_knowledge_graphs_student_id'), table_name='knowledge_graphs')
    op.create_index(op.f('ix_knowledge_graphs_student_id'), 'knowledge_graphs', ['student_id'], unique=False)
    op.add_column('contents', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_vector_id'), table_name='contents')
    op.create_index(op.f('ix_contents_vector_id'), 'contents', ['vector_id'], unique=False)
    op.create_index(op.f('ix_contents_created_by'), 'contents', ['created_by'], unique=False)
    op.add_column('content_vocabulary', sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_conversations_student_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
